FROM node:20-alpine

WORKDIR /app

COPY server/package.json ./server/package.json
RUN cd server \
  && npm install --omit=dev

COPY server /app/server

WORKDIR /app/server
EXPOSE 3000
CMD ["node", "index.js"]


