name: Deploy Backend to Server

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
      - 'Dockerfile.server'
      - 'docker-compose.server.yml'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify files present
        run: |
          set -euxo pipefail
          pwd
          ls -la
          ls -la server || true

      - name: Copy files to server (server/, Dockerfile.server, docker-compose.server.yml)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          # Avoid ** which may not expand; copy top-level files we need
          source: "./server/*,./Dockerfile.server,./docker-compose.server.yml"
          target: ${{ secrets.SERVER_WORKDIR }}
          debug: true

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            set -euo pipefail
            cd "${{ secrets.SERVER_WORKDIR }}"
            mkdir -p server
            cat > server/.env << 'EOF'
            PORT=3000
            GH_CLIENT_ID=${{ secrets.GH_CLIENT_ID }}
            GH_CLIENT_SECRET=${{ secrets.GH_CLIENT_SECRET }}
            FRONTEND_ORIGIN=${{ secrets.FRONTEND_ORIGIN }}
            GH_REDIRECT_URI=${{ secrets.GH_REDIRECT_URI }}
            GH_OAUTH_SCOPES=${{ secrets.GH_OAUTH_SCOPES }}
            EOF
            echo "Using external overlay network: prod_swecc-network"
            docker network inspect prod_swecc-network >/dev/null 2>&1 || { echo "Missing network prod_swecc-network" >&2; exit 1; }
            export DOCKER_BUILDKIT=1
            if docker compose version >/dev/null 2>&1; then
              docker compose -f docker-compose.server.yml up -d --build --remove-orphans
            else
              docker-compose -f docker-compose.server.yml up -d --build --remove-orphans
            fi
            echo "Deployed auth-server. Public health check:"
            curl -fsS --max-time 15 "${{ secrets.AUTH_SERVER_BASE_URL }}/health" || true


